Feature/supply rate
nearlend/nearlend-protocol pull request #69
Opened 2022-03-03 12:32 UTC by dariacherniak

2022-03-04 09:22 UTC, pahomas requested changes

2022-03-04 09:22 UTC, pahomas commented on contracts/dtoken/src/common.rs
>      pub fn get_exchange_rate(&self, underlying_balance: WBalance) -> Balance {
Is return value type - Balance? I guess it should be Ratio type

2022-03-04 09:22 UTC, pahomas commented on contracts/dtoken/src/common.rs
> +            return self.initial_exchange_rate * RATIO_DECIMALS;
initial_exchange_rate -> should be Ratio by default. So there is no need to use multiplier - RATIO_DECIMALS

2022-03-04 09:22 UTC, pahomas commented on contracts/dtoken/src/interest_model.rs
> +        assert!((Balance::from(underlying_balance) + Balance::from(total_borrows) - Balance::from(total_reserves)) > 0, "Cannot calculate utilization rate as contract has no assets");
If there are no assets, it means that util rate = 0. So we need to discuss this flow - not sure that assert good approach in this case.

2022-03-12 08:43 UTC, markblaize approved these changes

2022-03-12 08:45 UTC, merged