PR: User profile controller
nearlend/nearlend-protocol pull request #70
Opened 2022-03-04 09:09 UTC by TymofiiSavinov

Store user as user profile. Created methods:

1.  set_supply_amount, 
2. set_borrow_amount,
3. is_exist,
4. get_profile_index.

2022-03-04 10:03 UTC, pahomas requested changes

2022-03-11 14:29 UTC, markblaize requested changes

2022-03-11 14:29 UTC, markblaize commented on contracts/dtoken/src/withdraw.rs
> +        let user_profile = UserProfileDtoken::default();
@TymofiiSavinov UserProfile should be part of Dtoken storage

2022-03-11 14:29 UTC, markblaize commented on contracts/dtoken/src/user_profile.rs
> +#[near_bindgen]
@TymofiiSavinov we don't need a bindgen for internal structures

2022-03-11 14:29 UTC, markblaize commented on contracts/dtoken/src/user_profile.rs
> +pub enum Action {
@TymofiiSavinov do we use this anywhere?

2022-03-11 14:29 UTC, markblaize commented on contracts/dtoken/src/user_profile.rs
> +pub struct UserProfileDtoken {
@TymofiiSavinov we don't need a separate wrapper for user profiles, just make `user_profile_list` a part of dtoken

2022-03-11 14:29 UTC, markblaize commented on contracts/dtoken/src/supply.rs
> +        if user_profile.is_exist(self.get_signer_address().clone()) &&
@TymofiiSavinov 
we should create profile on Supply (if doesn't exist) 
and we should prevent Withdraw, Borrow, Repay if user profile doens't exist

2022-03-11 14:30 UTC, markblaize commented on contracts/controller/src/user_profile.rs
> +impl UserProfileController {
@TymofiiSavinov This should be part of Controller not a separate contract

2022-03-27 12:45 UTC, closed without merging