implemented get_total_borrows/supplies
nearlend/nearlend-protocol pull request #81
Opened 2022-03-17 14:31 UTC by dmytro-shash

2022-03-17 17:34 UTC, Pavel-Blaize commented
Task linked: [CU-23nfwkf Implement get_markets view method on controller](https://app.clickup.com/t/23nfwkf)

2022-03-18 21:49 UTC, pahomas requested changes

2022-03-18 21:49 UTC, pahomas commented on contracts/controller/src/borrows_supplies.rs
Please be carefull and use DRY principle. Can be replaced by:

    fn get_account_balance(&self, account_entry: Option<UnorderedMap<AccountId, Balance>>) -> WBalance {
        let mut balance: Balance = 0;

        if account_entry.is_some() {
            let account_borrow = account_entry.unwrap();

            for (asset, asset_amount) in account_borrow.iter() {
                let asset_price = self.get_price(asset.clone()).unwrap().value;

                balance += asset_price * asset_amount;
            }
        }

        U128(balance);
    }
    
    pub fn get_total_borrows(&self, account: AccountId) -> WBalance {
        return self.get_account_balance(self.account_borrows.get(&account));
    }

    pub fn get_total_supplies(&self, account: AccountId) -> WBalance {
        return self.get_account_balance(self.account_supplies.get(&account));
    }

2022-03-21 08:29 UTC, pahomas approved these changes

2022-03-21 08:30 UTC, merged