PR: Liquidation of borrow
nearlend/nearlend-protocol pull request #92
Opened 2022-03-24 09:19 UTC by convowork1

2022-03-27 09:39 UTC, markblaize requested changes

2022-03-27 09:39 UTC, markblaize commented on contracts/dtoken/src/liquidation.rs
> +                    "Liquidation failed, while tried to call controller ({:?})",
@convowork1 we cannot use `:?` in production as it inteded for debug only
"Liquidation failed, while tried to call controller ({:?})" -> "failed to liquidate on {}", self.get_controller_address()

2022-03-27 09:39 UTC, markblaize commented on contracts/dtoken/src/liquidation.rs
> +                String::from("withdraw_fail"),
@convowork1 withdraw_fail -> liquidation_fail

2022-03-27 09:39 UTC, markblaize commented on contracts/dtoken/src/liquidation.rs
> +            env::panic_str("");
@convowork1 panic should still have meaningful message, e.g. "failed to liquidate"

2022-03-27 09:39 UTC, markblaize commented on contracts/dtoken/src/liquidation.rs
> +    pub fn liquidation_repay_borrows_callback(
@convowork1 are we using this anywhere?

2022-03-27 09:39 UTC, markblaize commented on contracts/dtoken/src/ft.rs
> +                    AccountId::new_unchecked(String::from(memo_data["borrower"].as_str().unwrap()));
@convowork1 user input should alway be validated

2022-03-28 08:09 UTC, convowork1 commented on contracts/controller/src/liquidation.rs
> +            log!("Liquidation failed on borrow_repay call, revert changes...");
There is no this kind of logs in controller contract. It's only available for dtoken

2022-03-31 10:42 UTC, markblaize approved these changes

2022-03-31 10:42 UTC, merged